# golangci-lint configuration compatible with v1.62

version: "2"

run:
  timeout: 10m
  tests: false  # Disable test file linting to reduce noise

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck  # Disable errcheck completely for now

issues:
  max-same-issues: 5
  max-issues-per-linter: 10