# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - examples
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional linters
    - bodyclose
    - dupl
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  disable:
    - exhaustive
    - godox
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*os.File).Close
      - (*os.Process).Kill
      - os.WriteFile
      - os.MkdirAll
      - filepath.Walk
      - '(*github.com/jonwraymond/go-claude-code-sdk/pkg/errors.BaseError).WithDetail'
      - '(*github.com/jonwraymond/go-claude-code-sdk/pkg/errors.BaseError).WithRetryable'
      - '(*github.com/jonwraymond/go-claude-code-sdk/pkg/errors.BaseError).WithRequestID'
      - '(*github.com/jonwraymond/go-claude-code-sdk/pkg/errors.BaseError).WithHTTPStatus'

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 4

  goimports:
    local-prefixes: github.com/jonwraymond/go-claude-code-sdk

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/jonwraymond/go-claude-code-sdk)

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  revive:
    rules:
      - name: var-naming
        disabled: true
      - name: unexported-return
        disabled: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known patterns
    - linters:
        - lll
      source: "^//go:generate "

    # Exclude generated files
    - path: generated.go
      linters:
        - golint

    # Allow deprecated methods in tests
    - text: "SA1019.*Temporary.*deprecated"
      linters:
        - staticcheck
    
    # Allow nil pointer dereference in tests
    - path: _test\.go
      text: "SA5011"
      linters:
        - staticcheck

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false