# golangci-lint configuration for v2
linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - errcheck

run:
  timeout: 10m
  tests: false

issues:
  max-same-issues: 5
  max-issues-per-linter: 10