# golangci-lint configuration compatible with v1.62

version: 2

run:
  timeout: 10m
  tests: false  # Disable test file linting to reduce noise
  skip-dirs:
    - examples
    - tests

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck  # Disable errcheck completely for now

issues:
  max-same-issues: 5
  max-issues-per-linter: 10
  
  exclude-rules:
    # Allow deprecated methods
    - text: "SA1019.*deprecated"
      linters:
        - staticcheck