# golangci-lint configuration
run:
  timeout: 10m
  tests: false

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck

issues:
  max-same-issues: 5
  max-issues-per-linter: 10