# This workflow builds and deploys the documentation to GitHub Pages.
# It is triggered on pushes to the main branch.
name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      # Install the necessary Python packages to build the documentation.
      - run: pip install mkdocs-material
      # Deploy the documentation to the gh-pages branch.
      - run: mkdocs gh-deploy --force
