name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Validate tag
      run: |
        # Ensure tag follows semantic versioning
        if ! echo "${{ github.ref_name }}" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'; then
          echo "Tag does not follow semantic versioning"
          exit 1
        fi

    - name: Run tests
      run: |
        go test -v -race ./...

    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog from commits since last tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "No previous tag found, including all commits"
          COMMITS=$(git log --pretty=format:"- %s" HEAD)
        else
          echo "Generating changelog since $PREVIOUS_TAG"
          COMMITS=$(git log --pretty=format:"- %s" "$PREVIOUS_TAG"..HEAD)
        fi
        
        # Create changelog content
        cat > RELEASE_NOTES.md << EOF
        ## What's Changed
        
        $COMMITS
        
        **Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREVIOUS_TAG}...${{ github.ref_name }}
        EOF
        
        echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
        generate_release_notes: true

    - name: Publish release notification
      run: |
        echo "🎉 Released ${{ github.ref_name }}!"
        echo "View release: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"